#!/usr/bin/env python
from forvelki.parser import parser
from forvelki.program import executor
import sys
from forvelki.error import ForvelkiError


def execute_file(filename):
	try:
		f = file(filename)
		src = f.read()
	except IOError:
		print>>sys.stderr, "unable to read file %s" % filename
		sys.exit(1)
	else:
		pgm = parser.parse(src)
		for result in pgm.execute():
			print result

def interactive_interpreter():
	ex = executor()
	try:
		while 1:
			try:
				line = raw_input("fvl: ")
				pgm = parser.parse(line+"\n")
				if pgm:
					ex.feed(pgm[0])
			except ForvelkiError as err:
				print>>sys.stderr, "error:", err
			except KeyboardInterrupt:
				print
	except EOFError:
		print

if __name__ == "__main__":

	if len(sys.argv) > 2:
		print>>sys.stderr, "usage: %s filename" % sys.argv[0]
		sys.exit(1)
	
	if len(sys.argv) == 2:
		execute_file()
	else:
		interactive_interpreter()